# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mart.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'mart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmart.proto\"V\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05\x12\x10\n\x08quantity\x18\x05 \x01(\x05\"\x9b\x01\n\x05Order\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x14\n\x0cproduct_name\x18\x03 \x01(\t\x12\x18\n\x10product_category\x18\x04 \x01(\t\x12\x10\n\x08quantity\x18\x05 \x01(\x05\x12\x15\n\rproduct_price\x18\x06 \x01(\x05\x12\x13\n\x0btotle_price\x18\x07 \x01(\x05\"\x9d\x01\n\rUpdateProduct\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x63\x61tegory\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x12\n\x05price\x18\x04 \x01(\x05H\x02\x88\x01\x01\x12\x15\n\x08quantity\x18\x05 \x01(\x05H\x03\x88\x01\x01\x42\x07\n\x05_nameB\x0b\n\t_categoryB\x08\n\x06_priceB\x0b\n\t_quantity\"7\n\x14IncrementProductItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x64\x64_product\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCT']._serialized_start=14
  _globals['_PRODUCT']._serialized_end=100
  _globals['_ORDER']._serialized_start=103
  _globals['_ORDER']._serialized_end=258
  _globals['_UPDATEPRODUCT']._serialized_start=261
  _globals['_UPDATEPRODUCT']._serialized_end=418
  _globals['_INCREMENTPRODUCTITEM']._serialized_start=420
  _globals['_INCREMENTPRODUCTITEM']._serialized_end=475
# @@protoc_insertion_point(module_scope)
